---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/test.ngxconsultants.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp consulting.html $DEPLOYPATH
    - /bin/cp managed.html $DEPLOYPATH
    - /bin/cp specialized.html $DEPLOYPATH
    - /bin/cp verified.html $DEPLOYPATH
    - /bin/cp faq.html $DEPLOYPATH
    - /bin/cp careers.html $DEPLOYPATH
    - /bin/cp privacy.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
